language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=xenctrl
    - PINS="xenctrl:."
    - OCAML_VERSION="4.07"
  matrix:
    - DISTRO="debian-unstable"
